### ISSUE TITLE
Want to know

### ISSUE THREAD

**Issue by ghost** [iampavangandhi/Chatbot#2]
Hello Pavan! I hope you are really doing well! I have gone through with this project and made it using your code.
Could you pls tell me  which course you have followed for this to made this project?
It would be really helpful for me!
I am a complete beginner in web dev and wanna start learning from your followed course.

**Comment by iampavangandhi** [comment]
hi @varun7678, I did Data Structures in Real Life Projects by Prateek Narang, Coding Blocks. Link: [`here`](https://online.codingblocks.com/courses/data-structures-projects-using-javascript)
